// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: xfguyo8p9zs8FxMdioQAoN
import * as React from "react";
import { ContentfulCredentialsProvider } from "@plasmicpkgs/plasmic-contentful"; // plasmic-import: lXSCSEWn2xb/codeComponent

export default function GlobalContextsProvider(props) {
  const { children, contentfulCredentialsProviderProps } = props;
  return (
    <ContentfulCredentialsProvider
      {...contentfulCredentialsProviderProps}
      accessToken={
        contentfulCredentialsProviderProps &&
        "accessToken" in contentfulCredentialsProviderProps
          ? contentfulCredentialsProviderProps.accessToken
          : "aWvf6oSLTuqxKCxSUpokajdQr84hGQFE6zoJG7DVVLg"
      }
      environment={
        contentfulCredentialsProviderProps &&
        "environment" in contentfulCredentialsProviderProps
          ? contentfulCredentialsProviderProps.environment
          : "master"
      }
      space={
        contentfulCredentialsProviderProps &&
        "space" in contentfulCredentialsProviderProps
          ? contentfulCredentialsProviderProps.space
          : "lmfbwqzbh93n"
      }
    >
      {children}
    </ContentfulCredentialsProvider>
  );
}
