// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: dXyvLu7j1Po85PHwR2Uoy6
// Component: AtHLQN2bcfkz
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { AntdDropdown } from "@plasmicpkgs/antd5/skinny/registerDropdown"; // plasmic-import: zIDEYq9RgLG/codeComponent
import { AntdMenuItem } from "@plasmicpkgs/antd5/skinny/registerMenu"; // plasmic-import: QSmezaW-Gyu/codeComponent
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton"; // plasmic-import: bx9Xzvf5_eu/codeComponent
import Button2 from "../../Button2"; // plasmic-import: OykjTNwBMTc/component
import { useScreenVariants as useScreenVariantspRlysB5IYetu } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: PRlysB5iYETU/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic_copy_of_app_starter.module.css"; // plasmic-import: dXyvLu7j1Po85PHwR2Uoy6/projectcss
import sty from "./PlasmicHeader.module.css"; // plasmic-import: AtHLQN2bcfkz/css
import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: NsUyZTGzS_UE/icon
import Icon38Icon from "./icons/PlasmicIcon__Icon38"; // plasmic-import: fPFeR0cUxtTp/icon
import amercareLogopngCPupovUrnpaJ from "./images/amercareLogopng.png"; // plasmic-import: cPupovUrnpaJ/picture

createPlasmicElementProxy;

export const PlasmicHeader__VariantProps = new Array();

export const PlasmicHeader__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicHeader__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantspRlysB5IYetu()
  });
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.root
      )}
    >
      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__vAwMy)}
      >
        <p.PlasmicImg
          data-plasmic-name={"img"}
          data-plasmic-override={overrides.img}
          alt={""}
          className={classNames(sty.img)}
          displayHeight={"auto"}
          displayMaxHeight={"none"}
          displayMaxWidth={"none"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"300px"}
          src={{
            src: amercareLogopngCPupovUrnpaJ,
            fullWidth: 339,
            fullHeight: 127,
            aspectRatio: undefined
          }}
        />

        <AntdDropdown
          className={classNames("__wab_instance", sty.dropdown__b3MSh)}
          menuItems={() => (
            <React.Fragment>
              <AntdMenuItem
                className={classNames("__wab_instance", sty.menuItem__dnVk5)}
                key={"menu-item-1"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__t7Sgs
                  )}
                >
                  {"Menu item"}
                </div>
              </AntdMenuItem>
              <AntdMenuItem
                className={classNames("__wab_instance", sty.menuItem___4HQ3I)}
                key={"menu-item-2"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__tfAsV
                  )}
                >
                  {"Menu item"}
                </div>
              </AntdMenuItem>
            </React.Fragment>
          )}
          menuItemsJson={(() => {
            const __composite = [
              { type: null, value: "action1", label: null },
              { type: null, value: "action2", label: null },
              { type: null, label: null, children: null },
              { type: null, label: null },
              { type: null, label: null, children: null },
              { type: null, label: null, children: null },
              { type: null, label: null, children: null },
              { type: null, label: null, children: null },
              { type: null, label: null, children: null },
              { type: null, label: null },
              { type: null, label: null, children: null },
              { type: null, label: null, children: null }
            ];

            __composite["0"]["type"] = "group";
            __composite["0"]["label"] = "Ashtrays";
            __composite["1"]["type"] = "group";
            __composite["1"]["label"] = "Bibs";
            __composite["2"]["type"] = "submenu";
            __composite["2"]["label"] = "Cutlery";
            __composite["2"]["children"] = (() => {
              const __composite = [
                { type: null, label: null, children: null },
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null }
              ];

              __composite["0"]["type"] = "group";
              __composite["0"]["label"] = "Forks";
              __composite["0"]["children"] = [{ type: "item" }];
              __composite["1"]["type"] = "group";
              __composite["1"]["label"] = "Knives";
              __composite["2"]["type"] = "group";
              __composite["2"]["label"] = "Meal Kits";
              __composite["3"]["type"] = "group";
              __composite["3"]["label"] = "Serving Utensils and Accessories";
              __composite["4"]["type"] = "group";
              __composite["4"]["label"] = "Spoons";
              return __composite;
            })();
            __composite["3"]["type"] = "group";
            __composite["3"]["label"] = "Doilies";
            __composite["4"]["type"] = "submenu";
            __composite["4"]["label"] = "Guest Checks and Order Pads";
            __composite["4"]["children"] = (() => {
              const __composite = [
                { type: null, label: null, children: null },
                { type: null, label: null }
              ];

              __composite["0"]["type"] = "submenu";
              __composite["0"]["label"] = "Multiple Copy";
              __composite["0"]["children"] = (() => {
                const __composite = [
                  { type: null, label: null, children: null }
                ];

                __composite["0"]["type"] = "group";
                __composite["0"]["label"] = "Multi Copy - Carbon";
                __composite["0"]["children"] = (() => {
                  const __composite = [{ type: null, label: null }];
                  __composite["0"]["type"] = "group";
                  __composite["0"]["label"] = "Single Copy";
                  return __composite;
                })();
                return __composite;
              })();
              __composite["1"]["type"] = "group";
              __composite["1"]["label"] = "Single Copy";
              return __composite;
            })();
            __composite["5"]["type"] = "submenu";
            __composite["5"]["label"] = "Kids Products";
            __composite["5"]["children"] = (() => {
              const __composite = [
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null }
              ];

              __composite["0"]["type"] = "group";
              __composite["0"]["label"] = "Crayons";
              __composite["1"]["type"] = "group";
              __composite["1"]["label"] = "Kids Bibs";
              __composite["2"]["type"] = "group";
              __composite["2"]["label"] = "Kids Cups";
              __composite["3"]["type"] = "group";
              __composite["3"]["label"] = "Kids Kaps";
              __composite["4"]["type"] = "group";
              __composite["4"]["label"] = "Kids Placemats";
              return __composite;
            })();
            __composite["6"]["type"] = "submenu";
            __composite["6"]["label"] = "Disposable Cups and Lids";
            __composite["6"]["children"] = (() => {
              const __composite = [
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null }
              ];

              __composite["0"]["type"] = "group";
              __composite["0"]["label"] = "Cold Cups";
              __composite["1"]["type"] = "group";
              __composite["1"]["label"] = "Cup Carriers";
              __composite["2"]["type"] = "group";
              __composite["2"]["label"] = "Cup Sleeves";
              __composite["3"]["type"] = "group";
              __composite["3"]["label"] = "Hot Cups";
              __composite["4"]["type"] = "group";
              __composite["4"]["label"] = "Portion Cups";
              return __composite;
            })();
            __composite["7"]["type"] = "submenu";
            __composite["7"]["label"] = "Picks and Skewers";
            __composite["7"]["children"] = (() => {
              const __composite = [
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null, children: null },
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null }
              ];

              __composite["0"]["type"] = "group";
              __composite["0"]["label"] = "Arrow Picks";
              __composite["1"]["type"] = "group";
              __composite["1"]["label"] = "Bamboo Picks";
              __composite["2"]["type"] = "group";
              __composite["2"]["label"] = "Flag Picks";
              __composite["3"]["type"] = "group";
              __composite["3"]["label"] = "Party Picks";
              __composite["4"]["type"] = "group";
              __composite["4"]["label"] = "Prism Picks";
              __composite["5"]["type"] = "submenu";
              __composite["5"]["label"] = "Skewers";
              __composite["5"]["children"] = (() => {
                const __composite = [
                  { type: null, label: null, children: null },
                  { type: null, label: null }
                ];

                __composite["0"]["type"] = "group";
                __composite["0"]["label"] = "Bamboo Skewers";
                __composite["0"]["children"] = [{ type: "item" }];
                __composite["1"]["type"] = "group";
                __composite["1"]["label"] = "Wooden Skewers";
                return __composite;
              })();
              __composite["6"]["type"] = "group";
              __composite["6"]["label"] = "Sword Picks";
              __composite["7"]["type"] = "group";
              __composite["7"]["label"] = "Toothpicks";
              __composite["8"]["type"] = "group";
              __composite["8"]["label"] = "Pizza Stackers";
              return __composite;
            })();
            __composite["8"]["type"] = "submenu";
            __composite["8"]["label"] = "Register Rolls";
            __composite["8"]["children"] = (() => {
              const __composite = [
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null }
              ];

              __composite["0"]["type"] = "group";
              __composite["0"]["label"] = "Bond Register Rolls";
              __composite["1"]["type"] = "group";
              __composite["1"]["label"] = "Bond Register Rolls";
              __composite["2"]["type"] = "group";
              __composite["2"]["label"] = "Ink Ribbons";
              __composite["3"]["type"] = "group";
              __composite["3"]["label"] = "Thermal Register Rolls";
              return __composite;
            })();
            __composite["9"]["type"] = "group";
            __composite["9"]["label"] = "Steak Markers";
            __composite["10"]["type"] = "submenu";
            __composite["10"]["label"] = "Stirrers and Straws";
            __composite["10"]["children"] = (() => {
              const __composite = [
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null, children: null }
              ];

              __composite["0"]["type"] = "group";
              __composite["0"]["label"] = "Coffee Lid Stir and Plug Sticks";
              __composite["1"]["type"] = "group";
              __composite["1"]["label"] = "Coffee Stir Sticks";
              __composite["2"]["type"] = "group";
              __composite["2"]["label"] = "Sip Straws and Stirrers";
              __composite["3"]["type"] = "group";
              __composite["3"]["label"] = "Stirrers";
              __composite["4"]["type"] = "submenu";
              __composite["4"]["label"] = "Straws";
              __composite["4"]["children"] = (() => {
                const __composite = [
                  { type: null, label: null },
                  { type: null, label: null },
                  { type: null, label: null },
                  { type: null, label: null },
                  { type: null, label: null },
                  { type: null, label: null },
                  { type: null, label: null },
                  { type: null, label: null }
                ];

                __composite["0"]["type"] = "group";
                __composite["0"]["label"] = "Colossal StrawsGiant Straws";
                __composite["1"]["type"] = "group";
                __composite["1"]["label"] = "Giant Straws";
                __composite["2"]["type"] = "group";
                __composite["2"]["label"] = "Jumbo Straws";
                __composite["3"]["type"] = "group";
                __composite["3"]["label"] = "Paper Straws";
                __composite["4"]["type"] = "group";
                __composite["4"]["label"] = "PLA Straws";
                __composite["5"]["type"] = "group";
                __composite["5"]["label"] = "Poly Straws";
                __composite["6"]["type"] = "group";
                __composite["6"]["label"] = "Sip Straws and Stirrers";
                __composite["7"]["type"] = "group";
                __composite["7"]["label"] = "Super Jumbo Straws";
                return __composite;
              })();
              return __composite;
            })();
            __composite["11"]["type"] = "submenu";
            __composite["11"]["label"] = "Tabletop";
            __composite["11"]["children"] = (() => {
              const __composite = [
                { type: null, label: null },
                { type: null, label: null, children: null },
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null }
              ];

              __composite["0"]["type"] = "group";
              __composite["0"]["label"] = "Coasters";
              __composite["1"]["type"] = "group";
              __composite["1"]["label"] = "Cutlery";
              __composite["1"]["children"] = (() => {
                const __composite = [
                  { type: null, label: null, children: null },
                  { type: null, label: null },
                  { type: null, label: null },
                  { type: null, label: null },
                  { type: null, label: null }
                ];

                __composite["0"]["type"] = "group";
                __composite["0"]["label"] = "Forks";
                __composite["0"]["children"] = [];
                __composite["1"]["type"] = "group";
                __composite["1"]["label"] = "Knives";
                __composite["2"]["type"] = "group";
                __composite["2"]["label"] = "Meal Kits";
                __composite["3"]["type"] = "group";
                __composite["3"]["label"] = "Serving Utensils and Accessories";
                __composite["4"]["type"] = "group";
                __composite["4"]["label"] = "Spoons";
                return __composite;
              })();
              __composite["2"]["type"] = "group";
              __composite["2"]["label"] = "Lemon Wraps";
              __composite["3"]["type"] = "group";
              __composite["3"]["label"] = "Moist Towelettes";
              __composite["4"]["type"] = "group";
              __composite["4"]["label"] = "Napkins and Accessories";
              __composite["5"]["type"] = "group";
              __composite["5"]["label"] = "Placemats";
              __composite["6"]["type"] = "item";
              __composite["6"]["label"] = "Tablecovers";
              __composite["7"]["type"] = "group";
              __composite["7"]["label"] = "Tableware";
              return __composite;
            })();
            return __composite;
          })()}
        >
          <AntdButton
            className={classNames("__wab_instance", sty.button__v7K8Q)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__a7HTs
              )}
            >
              {"Front of the House"}
            </div>
          </AntdButton>
        </AntdDropdown>
        <AntdDropdown
          className={classNames("__wab_instance", sty.dropdown__en0W)}
          menuItems={() => (
            <React.Fragment>
              <AntdMenuItem
                className={classNames("__wab_instance", sty.menuItem___109Gx)}
                key={"menu-item-1"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hdUi
                  )}
                >
                  {"Menu item"}
                </div>
              </AntdMenuItem>
              <AntdMenuItem
                className={classNames("__wab_instance", sty.menuItem___27HUv)}
                key={"menu-item-2"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___2Ik8Q
                  )}
                >
                  {"Menu item"}
                </div>
              </AntdMenuItem>
            </React.Fragment>
          )}
          menuItemsJson={(() => {
            const __composite = [
              { type: null, value: "action1", label: null },
              { type: null, value: "action2", label: null, children: null },
              { type: null, label: null, children: null },
              { type: null, label: null },
              { type: null, label: null, children: null },
              { type: null, label: null, children: null },
              { type: null, label: null },
              { type: null, label: null, children: null },
              { type: null, label: null, children: null }
            ];

            __composite["0"]["type"] = "group";
            __composite["0"]["label"] = "Aprons";
            __composite["1"]["type"] = "submenu";
            __composite["1"]["label"] = "Baking Supplies";
            __composite["1"]["children"] = (() => {
              const __composite = [
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null }
              ];

              __composite["0"]["type"] = "group";
              __composite["0"]["label"] = "Baking Cups";
              __composite["1"]["type"] = "group";
              __composite["1"]["label"] = "Bun Pan Bags";
              __composite["2"]["type"] = "group";
              __composite["2"]["label"] = "Bun Rack Covers";
              __composite["3"]["type"] = "group";
              __composite["3"]["label"] = "High Heat Pan Liners";
              __composite["4"]["type"] = "group";
              __composite["4"]["label"] = "High Heat Roasting Bags";
              __composite["5"]["type"] = "group";
              __composite["5"]["label"] = "Steam Pan Liners";
              return __composite;
            })();
            __composite["2"]["type"] = "submenu";
            __composite["2"]["label"] = "Chef Hats and Hair Restraints";
            __composite["2"]["children"] = (() => {
              const __composite = [
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null }
              ];

              __composite["0"]["type"] = "group";
              __composite["0"]["label"] = "Beanie Chef Caps";
              __composite["1"]["type"] = "group";
              __composite["1"]["label"] = "Beard Protectors";
              __composite["2"]["type"] = "group";
              __composite["2"]["label"] = "Bouffant Caps";
              __composite["3"]["type"] = "group";
              __composite["3"]["label"] = "Chef Hats";
              __composite["4"]["type"] = "group";
              __composite["4"]["label"] = "Hairnets";
              __composite["5"]["type"] = "group";
              __composite["5"]["label"] = "Hairnet Dispensers";
              __composite["6"]["type"] = "group";
              __composite["6"]["label"] = "Paper Caps";
              return __composite;
            })();
            __composite["3"]["type"] = "group";
            __composite["3"]["label"] = "Chop Holders";
            __composite["4"]["type"] = "submenu";
            __composite["4"]["label"] = "Disposable Bags";
            __composite["4"]["children"] = (() => {
              const __composite = [
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null }
              ];

              __composite["0"]["type"] = "group";
              __composite["0"]["label"] = "Bun Pan Bags and Liners";
              __composite["1"]["type"] = "group";
              __composite["1"]["label"] = "Bun Rack Covers";
              __composite["2"]["type"] = "group";
              __composite["2"]["label"] = "Disposable Bag Racks";
              __composite["3"]["type"] = "group";
              __composite["3"]["label"] = "Food Storage Bags";
              __composite["4"]["type"] = "group";
              __composite["4"]["label"] = "High Heat Roasting Bags";
              __composite["5"]["type"] = "group";
              __composite["5"]["label"] = "Mesh Bags";
              __composite["6"]["type"] = "group";
              __composite["6"]["label"] = "Silverware Bags";
              __composite["7"]["type"] = "group";
              __composite["7"]["label"] = "Take-Out Bags";
              __composite["8"]["type"] = "group";
              __composite["8"]["label"] = "Zip Bags";
              return __composite;
            })();
            __composite["5"]["type"] = "submenu";
            __composite["5"]["label"] = "Food Labels";
            __composite["5"]["children"] = (() => {
              const __composite = [
                { type: null, label: null },
                { type: null, label: null }
              ];

              __composite["0"]["type"] = "group";
              __composite["0"]["label"] = "Food Rotation Labels";
              __composite["1"]["type"] = "group";
              __composite["1"]["label"] = "Security Seals";
              return __composite;
            })();
            __composite["6"]["type"] = "group";
            __composite["6"]["label"] = "Food Shells";
            __composite["7"]["type"] = "submenu";
            __composite["7"]["label"] = "Fry Oil Filtration";
            __composite["7"]["children"] = (() => {
              const __composite = [
                { type: null, label: null },
                { type: null, label: null }
              ];

              __composite["0"]["type"] = "group";
              __composite["0"]["label"] = "Filters";
              __composite["1"]["type"] = "group";
              __composite["1"]["label"] = "Filter Aids";
              return __composite;
            })();
            __composite["8"]["type"] = "submenu";
            __composite["8"]["label"] = "Gloves";
            __composite["8"]["children"] = (() => {
              const __composite = [
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null },
                { type: null, label: null }
              ];

              __composite["0"]["type"] = "group";
              __composite["0"]["label"] = "Glove Dispensers";
              __composite["1"]["type"] = "group";
              __composite["1"]["label"] = "Hybrid Gloves";
              __composite["2"]["type"] = "group";
              __composite["2"]["label"] = "Latex Gloves";
              __composite["3"]["type"] = "group";
              __composite["3"]["label"] = "Nitrile Gloves";
              __composite["4"]["type"] = "group";
              __composite["4"]["label"] = "Poly Gloves";
              __composite["5"]["type"] = "group";
              __composite["5"]["label"] = "Synthetic Gloves";
              __composite["6"]["type"] = "group";
              __composite["6"]["label"] = "Vinyl Gloves";
              __composite["7"]["type"] = "group";
              __composite["7"]["label"] = "Yellow Rubber Gloves";
              return __composite;
            })();
            return __composite;
          })()}
        >
          <AntdButton
            className={classNames("__wab_instance", sty.button__whEuj)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__dIdqr
              )}
            >
              {"Back of the House \n"}
            </div>
          </AntdButton>
        </AntdDropdown>
        <AntdDropdown
          className={classNames("__wab_instance", sty.dropdown__cSwX1)}
          menuItems={() => (
            <React.Fragment>
              <AntdMenuItem
                className={classNames("__wab_instance", sty.menuItem__ok7Zo)}
                key={"menu-item-1"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fwiGe
                  )}
                >
                  {"Menu item"}
                </div>
              </AntdMenuItem>
              <AntdMenuItem
                className={classNames("__wab_instance", sty.menuItem__tPfB0)}
                key={"menu-item-2"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___2Tlkq
                  )}
                >
                  {"Menu item"}
                </div>
              </AntdMenuItem>
            </React.Fragment>
          )}
          menuItemsJson={[
            { type: "item", value: "action1", label: "Action 1" },
            { type: "item", value: "action2", label: "Action 2" }
          ]}
        >
          <AntdButton
            className={classNames("__wab_instance", sty.button__gnswD)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__pHkcy
              )}
            >
              {"Janitorial "}
            </div>
          </AntdButton>
        </AntdDropdown>
        <AntdDropdown
          className={classNames("__wab_instance", sty.dropdown___0HzMo)}
          menuItems={() => (
            <React.Fragment>
              <AntdMenuItem
                className={classNames("__wab_instance", sty.menuItem__rkbP2)}
                key={"menu-item-1"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nrAAp
                  )}
                >
                  {"Menu item"}
                </div>
              </AntdMenuItem>
              <AntdMenuItem
                className={classNames("__wab_instance", sty.menuItem__t9Ewy)}
                key={"menu-item-2"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___3Tgdi
                  )}
                >
                  {"Menu item"}
                </div>
              </AntdMenuItem>
            </React.Fragment>
          )}
          menuItemsJson={[
            { type: "item", value: "action1", label: "Action 1" },
            { type: "item", value: "action2", label: "Action 2" }
          ]}
        >
          <AntdButton
            className={classNames("__wab_instance", sty.button__as2Q8)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__k0Xfc
              )}
            >
              {"news"}
            </div>
          </AntdButton>
        </AntdDropdown>
        <AntdButton className={classNames("__wab_instance", sty.button__tdfPy)}>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__uxClD
            )}
          >
            {"catalog"}
          </div>
        </AntdButton>
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__yo53V)}
        >
          <Button2
            className={classNames("__wab_instance", sty.button2__lxewr)}
            color={"clear"}
            endIcon={
              <Icon38Icon
                className={classNames(projectcss.all, sty.svg__ma4I0)}
                role={"img"}
              />
            }
            onClick={async event => {
              const $steps = {};
              $steps["goToAboutUs"] = true
                ? (() => {
                    const actionArgs = {
                      destination: __wrapUserFunction(
                        {
                          type: "InteractionArgLoc",
                          actionName: "navigation",
                          interactionUuid: "c_iUZuvIYfI",
                          componentUuid: "AtHLQN2bcfkz",
                          argName: "destination"
                        },
                        () => `/about-us`
                      )
                    };
                    return __wrapUserFunction(
                      {
                        type: "InteractionLoc",
                        actionName: "navigation",
                        interactionUuid: "c_iUZuvIYfI",
                        componentUuid: "AtHLQN2bcfkz"
                      },
                      () =>
                        (({ destination }) => {
                          location.assign(destination);
                        })?.apply(null, [actionArgs]),
                      actionArgs
                    );
                  })()
                : undefined;
              if (
                typeof $steps["goToAboutUs"] === "object" &&
                typeof $steps["goToAboutUs"].then === "function"
              ) {
                $steps["goToAboutUs"] = await __wrapUserPromise(
                  {
                    type: "InteractionLoc",
                    actionName: "navigation",
                    interactionUuid: "c_iUZuvIYfI",
                    componentUuid: "AtHLQN2bcfkz"
                  },
                  $steps["goToAboutUs"]
                );
              }
            }}
            startIcon={
              <ChecksvgIcon
                className={classNames(projectcss.all, sty.svg__s5Qm)}
                role={"img"}
              />
            }
            submitsForm={true}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__w949F
              )}
            >
              {"about us"}
            </div>
          </Button2>
          <Button2
            className={classNames("__wab_instance", sty.button2__smOw)}
            color={"clear"}
            endIcon={
              <Icon38Icon
                className={classNames(projectcss.all, sty.svg___5QPmb)}
                role={"img"}
              />
            }
            startIcon={
              <ChecksvgIcon
                className={classNames(projectcss.all, sty.svg__mtli2)}
                role={"img"}
              />
            }
            submitsForm={true}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___9Jfwp
              )}
            >
              {"Contact us"}
            </div>
          </Button2>
          <Button2
            className={classNames("__wab_instance", sty.button2___6DuVd)}
            endIcon={
              <Icon38Icon
                className={classNames(projectcss.all, sty.svg__nsgq4)}
                role={"img"}
              />
            }
            startIcon={
              <ChecksvgIcon
                className={classNames(projectcss.all, sty.svg__zICl)}
                role={"img"}
              />
            }
            submitsForm={true}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___8FYN
              )}
            >
              {"login"}
            </div>
          </Button2>
        </p.Stack>
        <AntdDropdown
          className={classNames("__wab_instance", sty.dropdown___5FJmT)}
          menuItems={() => (
            <React.Fragment>
              <AntdMenuItem
                className={classNames("__wab_instance", sty.menuItem___8TKfw)}
                key={"menu-item-1"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__zJs9A
                  )}
                >
                  {"Menu item"}
                </div>
              </AntdMenuItem>
              <AntdMenuItem
                className={classNames("__wab_instance", sty.menuItem__mpXo0)}
                key={"menu-item-2"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___4T49
                  )}
                >
                  {"Menu item"}
                </div>
              </AntdMenuItem>
            </React.Fragment>
          )}
          menuItemsJson={[
            { type: "item", value: "action1", label: "Action 1" },
            { type: "item", value: "action2", label: "Action 2" }
          ]}
        >
          <AntdButton
            className={classNames("__wab_instance", sty.button__wX9SB)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__tbpPv
              )}
            >
              {"Resources"}
            </div>
          </AntdButton>
        </AntdDropdown>
        {false ? (
          <div className={classNames(projectcss.all, sty.freeBox__xzrRa)}>
            <button
              className={classNames(
                projectcss.all,
                projectcss.button,
                projectcss.__wab_text,
                sty.button__bJfG
              )}
            >
              {"Sign up"}
            </button>
            {true ? (
              <Button2
                className={classNames("__wab_instance", sty.button2__u8ApE)}
                color={"clear"}
                endIcon={
                  <Icon38Icon
                    className={classNames(projectcss.all, sty.svg__h16Kj)}
                    role={"img"}
                  />
                }
                startIcon={
                  <ChecksvgIcon
                    className={classNames(projectcss.all, sty.svg__ackDt)}
                    role={"img"}
                  />
                }
                submitsForm={true}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ybGe4
                  )}
                >
                  {"Log in"}
                </div>
              </Button2>
            ) : null}
          </div>
        ) : null}
        <AntdDropdown
          className={classNames("__wab_instance", sty.dropdown__wYbp)}
          menuItems={() => (
            <React.Fragment>
              <AntdMenuItem
                className={classNames("__wab_instance", sty.menuItem__jpU3X)}
                key={"menu-item-1"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__b9Un9
                  )}
                >
                  {"Menu item"}
                </div>
              </AntdMenuItem>
              <AntdMenuItem
                className={classNames("__wab_instance", sty.menuItem__zJnrd)}
                key={"menu-item-2"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ckm
                  )}
                >
                  {"Menu item"}
                </div>
              </AntdMenuItem>
            </React.Fragment>
          )}
          menuItemsJson={[
            { type: "item", value: "action1", label: "Action 1" },
            { type: "item", value: "action2", label: "Action 2" }
          ]}
        >
          <AntdButton
            className={classNames("__wab_instance", sty.button___79Lqn)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__r5TAs
              )}
            >
              {"Safety & Industrial"}
            </div>
          </AntdButton>
        </AntdDropdown>
        <AntdDropdown
          className={classNames("__wab_instance", sty.dropdown__ev1RQ)}
          menuItems={() => (
            <React.Fragment>
              <AntdMenuItem
                className={classNames("__wab_instance", sty.menuItem__mgt5Y)}
                key={"menu-item-1"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jfR2T
                  )}
                >
                  {"Menu item"}
                </div>
              </AntdMenuItem>
              <AntdMenuItem
                className={classNames("__wab_instance", sty.menuItem__gSd8M)}
                key={"menu-item-2"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__axTxl
                  )}
                >
                  {"Menu item"}
                </div>
              </AntdMenuItem>
            </React.Fragment>
          )}
          menuItemsJson={[
            { type: "item", value: "action1", label: "Action 1" },
            { type: "item", value: "action2", label: "Action 2" }
          ]}
        >
          <AntdButton
            className={classNames("__wab_instance", sty.button__jfFmY)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ljlmt
              )}
            >
              {"PrimeWare Eco Products"}
            </div>
          </AntdButton>
        </AntdDropdown>
      </p.Stack>
      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__plk50)}
      />
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "img"],
  img: ["img"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHeader__ArgProps,
          internalVariantPropNames: PlasmicHeader__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicHeader__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHeader";
  } else {
    func.displayName = `PlasmicHeader.${nodeName}`;
  }
  return func;
}

export const PlasmicHeader = Object.assign(
  // Top-level PlasmicHeader renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    // Metadata about props expected for PlasmicHeader
    internalVariantProps: PlasmicHeader__VariantProps,
    internalArgProps: PlasmicHeader__ArgProps
  }
);

export default PlasmicHeader;
/* prettier-ignore-end */
