// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: dXyvLu7j1Po85PHwR2Uoy6
// Component: r9gkqCd2Tt2k
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import * as plasmicAuth from "@plasmicapp/react-web/lib/auth";
import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton"; // plasmic-import: bx9Xzvf5_eu/codeComponent
import Header from "../../Header"; // plasmic-import: AtHLQN2bcfkz/component
import Footer from "../../Footer"; // plasmic-import: 0oRBHM_nRQ2h/component
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic_copy_of_app_starter.module.css"; // plasmic-import: dXyvLu7j1Po85PHwR2Uoy6/projectcss
import sty from "./PlasmicPdp.module.css"; // plasmic-import: r9gkqCd2Tt2k/css
import Group4Icon from "./icons/PlasmicIcon__Group4"; // plasmic-import: PQFALSMM360t/icon
import Vector2Icon from "./icons/PlasmicIcon__Vector2"; // plasmic-import: t5RUWj1hUqLc/icon
import DividerIcon from "./icons/PlasmicIcon__Divider"; // plasmic-import: NpWHMZRxXxF8/icon
import HeartoutlineIcon from "./icons/PlasmicIcon__Heartoutline"; // plasmic-import: s0UARrtqBPWT/icon
import CartIcon from "./icons/PlasmicIcon__Cart"; // plasmic-import: 3XBD3ulcVhkv/icon
import UpDownSelectIcon from "./icons/PlasmicIcon__UpDownSelect"; // plasmic-import: 4CYF6gihOuuB/icon
import DownChevronIcon from "./icons/PlasmicIcon__DownChevron"; // plasmic-import: QaMpWq--Q0oH/icon
import StarfilledIcon from "./icons/PlasmicIcon__Starfilled"; // plasmic-import: XzYn0bVQUJB9/icon
import StaroutlineIcon from "./icons/PlasmicIcon__Staroutline"; // plasmic-import: 8cBBq5AKpX3i/icon
import Ellipse11Icon from "./icons/PlasmicIcon__Ellipse11"; // plasmic-import: c5v2vAZfhhNP/icon
import AntDesignheartFilledIcon from "./icons/PlasmicIcon__AntDesignheartFilled"; // plasmic-import: A6XRffB7rL_4/icon
import BicartIcon from "./icons/PlasmicIcon__Bicart"; // plasmic-import: 25h3Pfx-_Kgp/icon
import Polygon1Icon from "./icons/PlasmicIcon__Polygon1"; // plasmic-import: YpKzwcYzuEJE/icon
import ShapeIcon from "./icons/PlasmicIcon__Shape"; // plasmic-import: TU10tenGiP-4/icon
import RightIcon from "./icons/PlasmicIcon__Right"; // plasmic-import: ToCrGcnGAQmo/icon
import LeftIcon from "./icons/PlasmicIcon__Left"; // plasmic-import: 0HKKWF6gmwwA/icon
import Divider5Icon from "./icons/PlasmicIcon__Divider5"; // plasmic-import: nAe8nSAA2k35/icon
import group5EQskEjdCyay1 from "./images/group5.svg"; // plasmic-import: EQskEjdCyay1/picture
import group67F9Ig4U4P1W from "./images/group6.svg"; // plasmic-import: 7F9ig4u4p1-W/picture
import divider2KtKLi5KoDfh6 from "./images/divider2.svg"; // plasmic-import: KtKLi5KoDfh6/picture
import divider39DtZ6WOoZpkM from "./images/divider3.svg"; // plasmic-import: 9dtZ6wOoZpkM/picture
import divider4BxLqnHfKnG from "./images/divider4.svg"; // plasmic-import: bxLqnHFKn__g/picture
import frame4YDGulG6Mu4Ux from "./images/frame4.svg"; // plasmic-import: yDGulG6Mu4Ux/picture

createPlasmicElementProxy;

export const PlasmicPdp__VariantProps = new Array();

export const PlasmicPdp__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicPdp__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"freeBox"}
            data-plasmic-override={overrides.freeBox}
            className={classNames(projectcss.all, sty.freeBox)}
          >
            <div
              data-plasmic-name={"product"}
              data-plasmic-override={overrides.product}
              className={classNames(projectcss.all, sty.product)}
            >
              <div
                data-plasmic-name={"productCard"}
                data-plasmic-override={overrides.productCard}
                className={classNames(projectcss.all, sty.productCard)}
              >
                <div
                  data-plasmic-name={"sidebar"}
                  data-plasmic-override={overrides.sidebar}
                  className={classNames(projectcss.all, sty.sidebar)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"paymentMethods"}
                    data-plasmic-override={overrides.paymentMethods}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.paymentMethods)}
                  >
                    <div
                      data-plasmic-name={"visa"}
                      data-plasmic-override={overrides.visa}
                      className={classNames(projectcss.all, sty.visa)}
                    >
                      <div
                        data-plasmic-name={"group"}
                        data-plasmic-override={overrides.group}
                        className={classNames(projectcss.all, sty.group)}
                      >
                        <Group4Icon
                          className={classNames(projectcss.all, sty.svg__jkTey)}
                          role={"img"}
                        />

                        <Vector2Icon
                          className={classNames(projectcss.all, sty.svg__rw4V)}
                          role={"img"}
                        />
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"masterCard"}
                      data-plasmic-override={overrides.masterCard}
                      className={classNames(projectcss.all, sty.masterCard)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__fmctu)}
                        displayHeight={"41.999px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"53.985px"}
                        loading={"lazy"}
                        src={{
                          src: group5EQskEjdCyay1,
                          fullWidth: 53.985,
                          fullHeight: 41.999,
                          aspectRatio: 1.285714
                        }}
                      />
                    </div>
                    <div
                      data-plasmic-name={"payPal"}
                      data-plasmic-override={overrides.payPal}
                      className={classNames(projectcss.all, sty.payPal)}
                    >
                      <div
                        data-plasmic-name={"group2"}
                        data-plasmic-override={overrides.group2}
                        className={classNames(projectcss.all, sty.group2)}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__rfjmx)}
                          displayHeight={"19.784px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"78px"}
                          loading={"lazy"}
                          src={{
                            src: group67F9Ig4U4P1W,
                            fullWidth: 78,
                            fullHeight: 19.784,
                            aspectRatio: 3.9
                          }}
                        />
                      </div>
                    </div>
                  </p.Stack>
                  <div
                    data-plasmic-name={"accordion"}
                    data-plasmic-override={overrides.accordion}
                    className={classNames(projectcss.all, sty.accordion)}
                  >
                    <DividerIcon
                      className={classNames(projectcss.all, sty.svg__cm1Ae)}
                      role={"img"}
                    />

                    <div
                      data-plasmic-name={"panelOpen2"}
                      data-plasmic-override={overrides.panelOpen2}
                      className={classNames(projectcss.all, sty.panelOpen2)}
                    >
                      <div
                        data-plasmic-name={"list"}
                        data-plasmic-override={overrides.list}
                        className={classNames(projectcss.all, sty.list)}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__vAxAg)}
                          displayHeight={"1px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"525px"}
                          loading={"lazy"}
                          src={{
                            src: divider2KtKLi5KoDfh6,
                            fullWidth: 525,
                            fullHeight: 1,
                            aspectRatio: 525
                          }}
                        />

                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__zdgvf)}
                          displayHeight={"1px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"525px"}
                          loading={"lazy"}
                          src={{
                            src: divider39DtZ6WOoZpkM,
                            fullWidth: 525,
                            fullHeight: 1,
                            aspectRatio: 525
                          }}
                        />

                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__rkk3S)}
                          displayHeight={"1px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"525px"}
                          loading={"lazy"}
                          src={{
                            src: divider4BxLqnHfKnG,
                            fullWidth: 525,
                            fullHeight: 1,
                            aspectRatio: 525
                          }}
                        />

                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"column2"}
                          data-plasmic-override={overrides.column2}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.column2)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__gwqdB
                            )}
                          >
                            {"VALUE"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ySfcw
                            )}
                          >
                            {"5991"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__n0YiO
                            )}
                          >
                            {"10/12"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__d8OO
                            )}
                          >
                            {"10x6"}
                          </div>
                        </p.Stack>
                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"column1"}
                          data-plasmic-override={overrides.column1}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.column1)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__gGn81
                            )}
                          >
                            {"TYPE"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__sLf4F
                            )}
                          >
                            {"ITEM NUMBER"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__uiPXw
                            )}
                          >
                            {"PACK"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__eyKr
                            )}
                          >
                            {"TIER/HEIGHT"}
                          </div>
                        </p.Stack>
                      </div>
                      <div
                        data-plasmic-name={"list2"}
                        data-plasmic-override={overrides.list2}
                        className={classNames(projectcss.all, sty.list2)}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__og8To)}
                          displayHeight={"1px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"525px"}
                          loading={"lazy"}
                          src={{
                            src: divider2KtKLi5KoDfh6,
                            fullWidth: 525,
                            fullHeight: 1,
                            aspectRatio: 525
                          }}
                        />

                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__qj7Qg)}
                          displayHeight={"1px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"525px"}
                          loading={"lazy"}
                          src={{
                            src: divider39DtZ6WOoZpkM,
                            fullWidth: 525,
                            fullHeight: 1,
                            aspectRatio: 525
                          }}
                        />

                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__vOc4Y)}
                          displayHeight={"1px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"525px"}
                          loading={"lazy"}
                          src={{
                            src: divider4BxLqnHfKnG,
                            fullWidth: 525,
                            fullHeight: 1,
                            aspectRatio: 525
                          }}
                        />

                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"column22"}
                          data-plasmic-override={overrides.column22}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.column22)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__io6Iw
                            )}
                          >
                            {"811033012225"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__jkyC
                            )}
                          >
                            {"L: 16.93 IN W: 10.43 IN H:10.63 IN\n"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__igsS9
                            )}
                          >
                            {"1.086"}
                          </div>
                        </p.Stack>
                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"column12"}
                          data-plasmic-override={overrides.column12}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.column12)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___2BqSx
                            )}
                          >
                            {"INNER UPC"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__gHitL
                            )}
                          >
                            {"CASE DIMENSIONS"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__trAx8
                            )}
                          >
                            {"CASE CUBE"}
                          </div>
                        </p.Stack>
                      </div>
                      <div
                        data-plasmic-name={"list3"}
                        data-plasmic-override={overrides.list3}
                        className={classNames(projectcss.all, sty.list3)}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__yGgnu)}
                          displayHeight={"1px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"525px"}
                          loading={"lazy"}
                          src={{
                            src: divider2KtKLi5KoDfh6,
                            fullWidth: 525,
                            fullHeight: 1,
                            aspectRatio: 525
                          }}
                        />

                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__ccgi4)}
                          displayHeight={"1px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"525px"}
                          loading={"lazy"}
                          src={{
                            src: divider39DtZ6WOoZpkM,
                            fullWidth: 525,
                            fullHeight: 1,
                            aspectRatio: 525
                          }}
                        />

                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__fz5Q)}
                          displayHeight={"1px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"525px"}
                          loading={"lazy"}
                          src={{
                            src: divider4BxLqnHfKnG,
                            fullWidth: 525,
                            fullHeight: 1,
                            aspectRatio: 525
                          }}
                        />

                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"column23"}
                          data-plasmic-override={overrides.column23}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.column23)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ba4Gp
                            )}
                          >
                            {"12.85 lb"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__gkjxU
                            )}
                          >
                            {"00811033011389"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__nk1Rq
                            )}
                          >
                            {"811033011341"}
                          </div>
                        </p.Stack>
                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"column13"}
                          data-plasmic-override={overrides.column13}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.column13)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__fwvN
                            )}
                          >
                            {"CASE WEIGHT"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ieCum
                            )}
                          >
                            {"MASTER UPC"}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ria1I
                            )}
                          >
                            {"INDIVIDUAL UPC"}
                          </div>
                        </p.Stack>
                      </div>
                    </div>
                    <AntdButton
                      data-plasmic-name={"button"}
                      data-plasmic-override={overrides.button}
                      className={classNames("__wab_instance", sty.button)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__pAoUq
                        )}
                      >
                        {"print / copy"}
                      </div>
                    </AntdButton>
                  </div>
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"btnsolidregularicon"}
                    data-plasmic-override={overrides.btnsolidregularicon}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      sty.btnsolidregularicon
                    )}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"btnText"}
                      data-plasmic-override={overrides.btnText}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.btnText)}
                    >
                      <HeartoutlineIcon
                        className={classNames(projectcss.all, sty.svg___0K1CB)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__l96Ad
                        )}
                      >
                        {"Favourite"}
                      </div>
                    </p.Stack>
                  </p.Stack>
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"btnsolidregularicon2"}
                    data-plasmic-override={overrides.btnsolidregularicon2}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      sty.btnsolidregularicon2
                    )}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"btnText2"}
                      data-plasmic-override={overrides.btnText2}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.btnText2)}
                    >
                      <div
                        data-plasmic-name={"cart"}
                        data-plasmic-override={overrides.cart}
                        className={classNames(projectcss.all, sty.cart)}
                      >
                        <CartIcon
                          className={classNames(projectcss.all, sty.svg__p09G9)}
                          role={"img"}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__iixxA
                        )}
                      >
                        {"Add to cart"}
                      </div>
                    </p.Stack>
                  </p.Stack>
                  <div
                    data-plasmic-name={"inputdefault"}
                    data-plasmic-override={overrides.inputdefault}
                    className={classNames(projectcss.all, sty.inputdefault)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__rh51T
                      )}
                    >
                      {"1"}
                    </div>
                    <UpDownSelectIcon
                      className={classNames(projectcss.all, sty.svg__qYeeB)}
                      role={"img"}
                    />
                  </div>
                  <div
                    data-plasmic-name={"sizeOptions"}
                    data-plasmic-override={overrides.sizeOptions}
                    className={classNames(projectcss.all, sty.sizeOptions)}
                  >
                    <div
                      data-plasmic-name={"formdefaulticon"}
                      data-plasmic-override={overrides.formdefaulticon}
                      className={classNames(
                        projectcss.all,
                        sty.formdefaulticon
                      )}
                    >
                      <div
                        data-plasmic-name={"label"}
                        data-plasmic-override={overrides.label}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.label
                        )}
                      >
                        {"Size"}
                      </div>
                      <div
                        data-plasmic-name={"input"}
                        data-plasmic-override={overrides.input}
                        className={classNames(projectcss.all, sty.input)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__o2T5Z
                          )}
                        >
                          {"Please select"}
                        </div>
                        <DownChevronIcon
                          className={classNames(projectcss.all, sty.svg__lSqD0)}
                          role={"img"}
                        />
                      </div>
                    </div>
                  </div>
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"reviews"}
                    data-plasmic-override={overrides.reviews}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.reviews)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"rating"}
                      data-plasmic-override={overrides.rating}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.rating)}
                    >
                      <StarfilledIcon
                        className={classNames(projectcss.all, sty.svg__wIWk)}
                        role={"img"}
                      />

                      <StarfilledIcon
                        className={classNames(projectcss.all, sty.svg__u9XP9)}
                        role={"img"}
                      />

                      <StarfilledIcon
                        className={classNames(projectcss.all, sty.svg__b1Bq)}
                        role={"img"}
                      />

                      <StarfilledIcon
                        className={classNames(projectcss.all, sty.svg__nmGYf)}
                        role={"img"}
                      />

                      <StaroutlineIcon
                        className={classNames(projectcss.all, sty.svg__w0Suc)}
                        role={"img"}
                      />
                    </p.Stack>
                    <div
                      data-plasmic-name={"quantity"}
                      data-plasmic-override={overrides.quantity}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.quantity
                      )}
                    >
                      {"12 reviews"}
                    </div>
                  </p.Stack>
                  <div
                    data-plasmic-name={"price"}
                    data-plasmic-override={overrides.price}
                    className={classNames(projectcss.all, sty.price)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"price2"}
                      data-plasmic-override={overrides.price2}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.price2)}
                    >
                      <div
                        data-plasmic-name={"price3"}
                        data-plasmic-override={overrides.price3}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.price3
                        )}
                      >
                        {"\u20b9400"}
                      </div>
                    </p.Stack>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qaJ7Z
                    )}
                  >
                    {
                      "These Cutlery Kits contain a black plastic fork and knife. The utensils are made from durable, heavy weight plastic for a high-quality dining experience. These kits are a sturdy and convenient option for any takeout food establishment."
                    }
                  </div>
                </div>
                <div
                  data-plasmic-name={"productGallery"}
                  data-plasmic-override={overrides.productGallery}
                  className={classNames(projectcss.all, sty.productGallery)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"imagesPreview"}
                    data-plasmic-override={overrides.imagesPreview}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.imagesPreview)}
                  >
                    <div
                      data-plasmic-name={"image"}
                      data-plasmic-override={overrides.image}
                      className={classNames(projectcss.all, sty.image)}
                    />

                    <div
                      data-plasmic-name={"image2"}
                      data-plasmic-override={overrides.image2}
                      className={classNames(projectcss.all, sty.image2)}
                    />

                    <div
                      data-plasmic-name={"image3"}
                      data-plasmic-override={overrides.image3}
                      className={classNames(projectcss.all, sty.image3)}
                    />

                    <div
                      data-plasmic-name={"image4"}
                      data-plasmic-override={overrides.image4}
                      className={classNames(projectcss.all, sty.image4)}
                    />
                  </p.Stack>
                  <div
                    data-plasmic-name={"image6"}
                    data-plasmic-override={overrides.image6}
                    className={classNames(projectcss.all, sty.image6)}
                  >
                    <div
                      data-plasmic-name={"figmaPaste"}
                      data-plasmic-override={overrides.figmaPaste}
                      className={classNames(projectcss.all, sty.figmaPaste)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__duyfk
                        )}
                      >
                        {"    Related Products"}
                      </div>
                      <div
                        data-plasmic-name={"rectangle20"}
                        data-plasmic-override={overrides.rectangle20}
                        className={classNames(projectcss.all, sty.rectangle20)}
                      />

                      <div
                        data-plasmic-name={"rectangle21"}
                        data-plasmic-override={overrides.rectangle21}
                        className={classNames(projectcss.all, sty.rectangle21)}
                      />

                      <div
                        data-plasmic-name={"rectangle22"}
                        data-plasmic-override={overrides.rectangle22}
                        className={classNames(projectcss.all, sty.rectangle22)}
                      />

                      <div
                        data-plasmic-name={"rectangle25"}
                        data-plasmic-override={overrides.rectangle25}
                        className={classNames(projectcss.all, sty.rectangle25)}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___4GP9K
                        )}
                      >
                        {"NEW"}
                      </div>
                      <Ellipse11Icon
                        className={classNames(projectcss.all, sty.svg__anyPa)}
                        role={"img"}
                      />

                      <AntDesignheartFilledIcon
                        className={classNames(projectcss.all, sty.svg__jZmAt)}
                        role={"img"}
                      />

                      <div
                        data-plasmic-name={"image7"}
                        data-plasmic-override={overrides.image7}
                        className={classNames(projectcss.all, sty.image7)}
                      />

                      <div
                        data-plasmic-name={"rectangle26"}
                        data-plasmic-override={overrides.rectangle26}
                        className={classNames(projectcss.all, sty.rectangle26)}
                      >
                        <BicartIcon
                          className={classNames(projectcss.all, sty.svg___3RsV)}
                          role={"img"}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__sU7PI
                          )}
                        >
                          {"Add to cart"}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"rectangle27"}
                        data-plasmic-override={overrides.rectangle27}
                        className={classNames(projectcss.all, sty.rectangle27)}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__gMcJh
                        )}
                      >
                        {"NEW"}
                      </div>
                      <Ellipse11Icon
                        className={classNames(projectcss.all, sty.svg__hQpuR)}
                        role={"img"}
                      />

                      <AntDesignheartFilledIcon
                        className={classNames(projectcss.all, sty.svg___5MvXk)}
                        role={"img"}
                      />

                      <div
                        data-plasmic-name={"rectangle28"}
                        data-plasmic-override={overrides.rectangle28}
                        className={classNames(projectcss.all, sty.rectangle28)}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___5X3Br
                        )}
                      >
                        {"NEW"}
                      </div>
                      <Ellipse11Icon
                        className={classNames(projectcss.all, sty.svg__fbLj)}
                        role={"img"}
                      />

                      <AntDesignheartFilledIcon
                        className={classNames(projectcss.all, sty.svg__ySIg)}
                        role={"img"}
                      />

                      <Ellipse11Icon
                        className={classNames(projectcss.all, sty.svg__zKgPm)}
                        role={"img"}
                      />

                      <AntDesignheartFilledIcon
                        className={classNames(projectcss.all, sty.svg__eoc5U)}
                        role={"img"}
                      />

                      <div
                        data-plasmic-name={"image8"}
                        data-plasmic-override={overrides.image8}
                        className={classNames(projectcss.all, sty.image8)}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___3CE5C
                        )}
                      >
                        {"GLOVE, EXAM GRADE, BLACK"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___2Nvym
                        )}
                      >
                        {"\u20b9400.22"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__eCrS
                        )}
                      >
                        {"GLOVE, EXAM GRDE GRAPE"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___9TrSj
                        )}
                      >
                        {"GLOVE, NITRA-MED HEAVY, NITRILE"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ob3Ik
                        )}
                      >
                        {"\u20b9412.00"}
                      </div>
                      <div
                        data-plasmic-name={"image9"}
                        data-plasmic-override={overrides.image9}
                        className={classNames(projectcss.all, sty.image9)}
                      />

                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__k3CSl)}
                        displayHeight={"24px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"24px"}
                        loading={"lazy"}
                        src={{
                          src: frame4YDGulG6Mu4Ux,
                          fullWidth: 24,
                          fullHeight: 24,
                          aspectRatio: 1
                        }}
                      />

                      <div
                        data-plasmic-name={"rectangle30"}
                        data-plasmic-override={overrides.rectangle30}
                        className={classNames(projectcss.all, sty.rectangle30)}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___2OAsJ
                        )}
                      >
                        {"Quick View"}
                      </div>
                      <Polygon1Icon
                        className={classNames(projectcss.all, sty.svg__x5Wli)}
                        role={"img"}
                      />

                      <div
                        data-plasmic-name={"rectangle31"}
                        data-plasmic-override={overrides.rectangle31}
                        className={classNames(projectcss.all, sty.rectangle31)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__s2TlC
                          )}
                        >
                          {"Add to cart"}
                        </div>
                        <BicartIcon
                          className={classNames(projectcss.all, sty.svg__gkUwc)}
                          role={"img"}
                        />
                      </div>
                      <div
                        data-plasmic-name={"rectangle32"}
                        data-plasmic-override={overrides.rectangle32}
                        className={classNames(projectcss.all, sty.rectangle32)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___2OUtn
                          )}
                        >
                          {"Add to cart"}
                        </div>
                        <BicartIcon
                          className={classNames(projectcss.all, sty.svg__dmmK)}
                          role={"img"}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__eQ7Ve
                        )}
                      >
                        {"\u20b9410.00"}
                      </div>
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"nextBtn"}
                    data-plasmic-override={overrides.nextBtn}
                    className={classNames(projectcss.all, sty.nextBtn)}
                  >
                    <ShapeIcon
                      className={classNames(projectcss.all, sty.svg__g1M4M)}
                      role={"img"}
                    />

                    <RightIcon
                      className={classNames(projectcss.all, sty.svg__yn4Xb)}
                      role={"img"}
                    />
                  </div>
                  <div
                    data-plasmic-name={"prevBtn"}
                    data-plasmic-override={overrides.prevBtn}
                    className={classNames(projectcss.all, sty.prevBtn)}
                  >
                    <ShapeIcon
                      className={classNames(projectcss.all, sty.svg__xto5N)}
                      role={"img"}
                    />

                    <LeftIcon
                      className={classNames(projectcss.all, sty.svg__tdW3F)}
                      role={"img"}
                    />
                  </div>
                </div>
                <Divider5Icon
                  className={classNames(projectcss.all, sty.svg__vzkjR)}
                  role={"img"}
                />

                <p.Stack
                  as={"div"}
                  data-plasmic-name={"tabs"}
                  data-plasmic-override={overrides.tabs}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.tabs)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"tab"}
                    data-plasmic-override={overrides.tab}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.tab)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ptSF
                      )}
                    >
                      {"General info"}
                    </div>
                  </p.Stack>
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"tab2"}
                    data-plasmic-override={overrides.tab2}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.tab2)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__riyhK
                      )}
                    >
                      {"Product details"}
                    </div>
                  </p.Stack>
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"tab3"}
                    data-plasmic-override={overrides.tab3}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.tab3)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"inner"}
                      data-plasmic-override={overrides.inner}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.inner)}
                    >
                      <div
                        data-plasmic-name={"reviews2"}
                        data-plasmic-override={overrides.reviews2}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.reviews2
                        )}
                      >
                        {"Reviews "}
                      </div>
                    </p.Stack>
                  </p.Stack>
                </p.Stack>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nlAlS
                  )}
                >
                  {"GLOVE, HOUSEHOLD, NEPTUNE YELLOW, FLOCK LINED, PF"}
                </div>
              </div>
              <Header
                data-plasmic-name={"header"}
                data-plasmic-override={overrides.header}
                className={classNames("__wab_instance", sty.header)}
              />

              <Divider5Icon
                className={classNames(projectcss.all, sty.svg___1NeFl)}
                role={"img"}
              />

              <Divider5Icon
                className={classNames(projectcss.all, sty.svg__iCh8)}
                role={"img"}
              />
            </div>
            <Footer
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames("__wab_instance", sty.footer)}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "freeBox",
    "product",
    "productCard",
    "sidebar",
    "paymentMethods",
    "visa",
    "group",
    "masterCard",
    "payPal",
    "group2",
    "accordion",
    "panelOpen2",
    "list",
    "column2",
    "column1",
    "list2",
    "column22",
    "column12",
    "list3",
    "column23",
    "column13",
    "button",
    "btnsolidregularicon",
    "btnText",
    "btnsolidregularicon2",
    "btnText2",
    "cart",
    "inputdefault",
    "sizeOptions",
    "formdefaulticon",
    "label",
    "input",
    "reviews",
    "rating",
    "quantity",
    "price",
    "price2",
    "price3",
    "productGallery",
    "imagesPreview",
    "image",
    "image2",
    "image3",
    "image4",
    "image6",
    "figmaPaste",
    "rectangle20",
    "rectangle21",
    "rectangle22",
    "rectangle25",
    "image7",
    "rectangle26",
    "rectangle27",
    "rectangle28",
    "image8",
    "image9",
    "rectangle30",
    "rectangle31",
    "rectangle32",
    "nextBtn",
    "prevBtn",
    "tabs",
    "tab",
    "tab2",
    "tab3",
    "inner",
    "reviews2",
    "header",
    "footer"
  ],

  freeBox: [
    "freeBox",
    "product",
    "productCard",
    "sidebar",
    "paymentMethods",
    "visa",
    "group",
    "masterCard",
    "payPal",
    "group2",
    "accordion",
    "panelOpen2",
    "list",
    "column2",
    "column1",
    "list2",
    "column22",
    "column12",
    "list3",
    "column23",
    "column13",
    "button",
    "btnsolidregularicon",
    "btnText",
    "btnsolidregularicon2",
    "btnText2",
    "cart",
    "inputdefault",
    "sizeOptions",
    "formdefaulticon",
    "label",
    "input",
    "reviews",
    "rating",
    "quantity",
    "price",
    "price2",
    "price3",
    "productGallery",
    "imagesPreview",
    "image",
    "image2",
    "image3",
    "image4",
    "image6",
    "figmaPaste",
    "rectangle20",
    "rectangle21",
    "rectangle22",
    "rectangle25",
    "image7",
    "rectangle26",
    "rectangle27",
    "rectangle28",
    "image8",
    "image9",
    "rectangle30",
    "rectangle31",
    "rectangle32",
    "nextBtn",
    "prevBtn",
    "tabs",
    "tab",
    "tab2",
    "tab3",
    "inner",
    "reviews2",
    "header",
    "footer"
  ],

  product: [
    "product",
    "productCard",
    "sidebar",
    "paymentMethods",
    "visa",
    "group",
    "masterCard",
    "payPal",
    "group2",
    "accordion",
    "panelOpen2",
    "list",
    "column2",
    "column1",
    "list2",
    "column22",
    "column12",
    "list3",
    "column23",
    "column13",
    "button",
    "btnsolidregularicon",
    "btnText",
    "btnsolidregularicon2",
    "btnText2",
    "cart",
    "inputdefault",
    "sizeOptions",
    "formdefaulticon",
    "label",
    "input",
    "reviews",
    "rating",
    "quantity",
    "price",
    "price2",
    "price3",
    "productGallery",
    "imagesPreview",
    "image",
    "image2",
    "image3",
    "image4",
    "image6",
    "figmaPaste",
    "rectangle20",
    "rectangle21",
    "rectangle22",
    "rectangle25",
    "image7",
    "rectangle26",
    "rectangle27",
    "rectangle28",
    "image8",
    "image9",
    "rectangle30",
    "rectangle31",
    "rectangle32",
    "nextBtn",
    "prevBtn",
    "tabs",
    "tab",
    "tab2",
    "tab3",
    "inner",
    "reviews2",
    "header"
  ],

  productCard: [
    "productCard",
    "sidebar",
    "paymentMethods",
    "visa",
    "group",
    "masterCard",
    "payPal",
    "group2",
    "accordion",
    "panelOpen2",
    "list",
    "column2",
    "column1",
    "list2",
    "column22",
    "column12",
    "list3",
    "column23",
    "column13",
    "button",
    "btnsolidregularicon",
    "btnText",
    "btnsolidregularicon2",
    "btnText2",
    "cart",
    "inputdefault",
    "sizeOptions",
    "formdefaulticon",
    "label",
    "input",
    "reviews",
    "rating",
    "quantity",
    "price",
    "price2",
    "price3",
    "productGallery",
    "imagesPreview",
    "image",
    "image2",
    "image3",
    "image4",
    "image6",
    "figmaPaste",
    "rectangle20",
    "rectangle21",
    "rectangle22",
    "rectangle25",
    "image7",
    "rectangle26",
    "rectangle27",
    "rectangle28",
    "image8",
    "image9",
    "rectangle30",
    "rectangle31",
    "rectangle32",
    "nextBtn",
    "prevBtn",
    "tabs",
    "tab",
    "tab2",
    "tab3",
    "inner",
    "reviews2"
  ],

  sidebar: [
    "sidebar",
    "paymentMethods",
    "visa",
    "group",
    "masterCard",
    "payPal",
    "group2",
    "accordion",
    "panelOpen2",
    "list",
    "column2",
    "column1",
    "list2",
    "column22",
    "column12",
    "list3",
    "column23",
    "column13",
    "button",
    "btnsolidregularicon",
    "btnText",
    "btnsolidregularicon2",
    "btnText2",
    "cart",
    "inputdefault",
    "sizeOptions",
    "formdefaulticon",
    "label",
    "input",
    "reviews",
    "rating",
    "quantity",
    "price",
    "price2",
    "price3"
  ],

  paymentMethods: [
    "paymentMethods",
    "visa",
    "group",
    "masterCard",
    "payPal",
    "group2"
  ],

  visa: ["visa", "group"],
  group: ["group"],
  masterCard: ["masterCard"],
  payPal: ["payPal", "group2"],
  group2: ["group2"],
  accordion: [
    "accordion",
    "panelOpen2",
    "list",
    "column2",
    "column1",
    "list2",
    "column22",
    "column12",
    "list3",
    "column23",
    "column13",
    "button"
  ],

  panelOpen2: [
    "panelOpen2",
    "list",
    "column2",
    "column1",
    "list2",
    "column22",
    "column12",
    "list3",
    "column23",
    "column13"
  ],

  list: ["list", "column2", "column1"],
  column2: ["column2"],
  column1: ["column1"],
  list2: ["list2", "column22", "column12"],
  column22: ["column22"],
  column12: ["column12"],
  list3: ["list3", "column23", "column13"],
  column23: ["column23"],
  column13: ["column13"],
  button: ["button"],
  btnsolidregularicon: ["btnsolidregularicon", "btnText"],
  btnText: ["btnText"],
  btnsolidregularicon2: ["btnsolidregularicon2", "btnText2", "cart"],
  btnText2: ["btnText2", "cart"],
  cart: ["cart"],
  inputdefault: ["inputdefault"],
  sizeOptions: ["sizeOptions", "formdefaulticon", "label", "input"],
  formdefaulticon: ["formdefaulticon", "label", "input"],
  label: ["label"],
  input: ["input"],
  reviews: ["reviews", "rating", "quantity"],
  rating: ["rating"],
  quantity: ["quantity"],
  price: ["price", "price2", "price3"],
  price2: ["price2", "price3"],
  price3: ["price3"],
  productGallery: [
    "productGallery",
    "imagesPreview",
    "image",
    "image2",
    "image3",
    "image4",
    "image6",
    "figmaPaste",
    "rectangle20",
    "rectangle21",
    "rectangle22",
    "rectangle25",
    "image7",
    "rectangle26",
    "rectangle27",
    "rectangle28",
    "image8",
    "image9",
    "rectangle30",
    "rectangle31",
    "rectangle32",
    "nextBtn",
    "prevBtn"
  ],

  imagesPreview: ["imagesPreview", "image", "image2", "image3", "image4"],
  image: ["image"],
  image2: ["image2"],
  image3: ["image3"],
  image4: ["image4"],
  image6: [
    "image6",
    "figmaPaste",
    "rectangle20",
    "rectangle21",
    "rectangle22",
    "rectangle25",
    "image7",
    "rectangle26",
    "rectangle27",
    "rectangle28",
    "image8",
    "image9",
    "rectangle30",
    "rectangle31",
    "rectangle32"
  ],

  figmaPaste: [
    "figmaPaste",
    "rectangle20",
    "rectangle21",
    "rectangle22",
    "rectangle25",
    "image7",
    "rectangle26",
    "rectangle27",
    "rectangle28",
    "image8",
    "image9",
    "rectangle30",
    "rectangle31",
    "rectangle32"
  ],

  rectangle20: ["rectangle20"],
  rectangle21: ["rectangle21"],
  rectangle22: ["rectangle22"],
  rectangle25: ["rectangle25"],
  image7: ["image7"],
  rectangle26: ["rectangle26"],
  rectangle27: ["rectangle27"],
  rectangle28: ["rectangle28"],
  image8: ["image8"],
  image9: ["image9"],
  rectangle30: ["rectangle30"],
  rectangle31: ["rectangle31"],
  rectangle32: ["rectangle32"],
  nextBtn: ["nextBtn"],
  prevBtn: ["prevBtn"],
  tabs: ["tabs", "tab", "tab2", "tab3", "inner", "reviews2"],
  tab: ["tab"],
  tab2: ["tab2"],
  tab3: ["tab3", "inner", "reviews2"],
  inner: ["inner", "reviews2"],
  reviews2: ["reviews2"],
  header: ["header"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicPdp__ArgProps,
          internalVariantPropNames: PlasmicPdp__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicPdp__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPdp";
  } else {
    func.displayName = `PlasmicPdp.${nodeName}`;
  }
  return func;
}

function withPlasmicPageGuard(WrappedComponent) {
  const PageGuard = props => (
    <p.PlasmicPageGuard
      minRole={null}
      appId={"dXyvLu7j1Po85PHwR2Uoy6"}
      authorizeEndpoint={"https://studio.plasmic.app/authorize"}
      canTriggerLogin={true}
    >
      <WrappedComponent {...props} />
    </p.PlasmicPageGuard>
  );

  return PageGuard;
}

function withUsePlasmicAuth(WrappedComponent) {
  const WithUsePlasmicAuthComponent = props => {
    const dataSourceCtx = usePlasmicDataSourceContext() ?? {};
    const { isUserLoading, user, token } = plasmicAuth.usePlasmicAuth({
      appId: "dXyvLu7j1Po85PHwR2Uoy6"
    });
    return (
      <p.PlasmicDataSourceContextProvider
        value={{
          ...dataSourceCtx,
          isUserLoading,
          userAuthToken: token,
          user
        }}
      >
        <WrappedComponent {...props} />
      </p.PlasmicDataSourceContextProvider>
    );
  };
  return WithUsePlasmicAuthComponent;
}

export const PlasmicPdp = Object.assign(
  // Top-level PlasmicPdp renders the root element
  withUsePlasmicAuth(withPlasmicPageGuard(makeNodeComponent("root"))),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    product: makeNodeComponent("product"),
    productCard: makeNodeComponent("productCard"),
    sidebar: makeNodeComponent("sidebar"),
    paymentMethods: makeNodeComponent("paymentMethods"),
    visa: makeNodeComponent("visa"),
    group: makeNodeComponent("group"),
    masterCard: makeNodeComponent("masterCard"),
    payPal: makeNodeComponent("payPal"),
    group2: makeNodeComponent("group2"),
    accordion: makeNodeComponent("accordion"),
    panelOpen2: makeNodeComponent("panelOpen2"),
    list: makeNodeComponent("list"),
    column2: makeNodeComponent("column2"),
    column1: makeNodeComponent("column1"),
    list2: makeNodeComponent("list2"),
    column22: makeNodeComponent("column22"),
    column12: makeNodeComponent("column12"),
    list3: makeNodeComponent("list3"),
    column23: makeNodeComponent("column23"),
    column13: makeNodeComponent("column13"),
    button: makeNodeComponent("button"),
    btnsolidregularicon: makeNodeComponent("btnsolidregularicon"),
    btnText: makeNodeComponent("btnText"),
    btnsolidregularicon2: makeNodeComponent("btnsolidregularicon2"),
    btnText2: makeNodeComponent("btnText2"),
    cart: makeNodeComponent("cart"),
    inputdefault: makeNodeComponent("inputdefault"),
    sizeOptions: makeNodeComponent("sizeOptions"),
    formdefaulticon: makeNodeComponent("formdefaulticon"),
    label: makeNodeComponent("label"),
    input: makeNodeComponent("input"),
    reviews: makeNodeComponent("reviews"),
    rating: makeNodeComponent("rating"),
    quantity: makeNodeComponent("quantity"),
    price: makeNodeComponent("price"),
    price2: makeNodeComponent("price2"),
    price3: makeNodeComponent("price3"),
    productGallery: makeNodeComponent("productGallery"),
    imagesPreview: makeNodeComponent("imagesPreview"),
    image: makeNodeComponent("image"),
    image2: makeNodeComponent("image2"),
    image3: makeNodeComponent("image3"),
    image4: makeNodeComponent("image4"),
    image6: makeNodeComponent("image6"),
    figmaPaste: makeNodeComponent("figmaPaste"),
    rectangle20: makeNodeComponent("rectangle20"),
    rectangle21: makeNodeComponent("rectangle21"),
    rectangle22: makeNodeComponent("rectangle22"),
    rectangle25: makeNodeComponent("rectangle25"),
    image7: makeNodeComponent("image7"),
    rectangle26: makeNodeComponent("rectangle26"),
    rectangle27: makeNodeComponent("rectangle27"),
    rectangle28: makeNodeComponent("rectangle28"),
    image8: makeNodeComponent("image8"),
    image9: makeNodeComponent("image9"),
    rectangle30: makeNodeComponent("rectangle30"),
    rectangle31: makeNodeComponent("rectangle31"),
    rectangle32: makeNodeComponent("rectangle32"),
    nextBtn: makeNodeComponent("nextBtn"),
    prevBtn: makeNodeComponent("prevBtn"),
    tabs: makeNodeComponent("tabs"),
    tab: makeNodeComponent("tab"),
    tab2: makeNodeComponent("tab2"),
    tab3: makeNodeComponent("tab3"),
    inner: makeNodeComponent("inner"),
    reviews2: makeNodeComponent("reviews2"),
    header: makeNodeComponent("header"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicPdp
    internalVariantProps: PlasmicPdp__VariantProps,
    internalArgProps: PlasmicPdp__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicPdp;
/* prettier-ignore-end */
